spring:
  datasource:
    url: jdbc:postgresql://ballast.proxy.rlwy.net:50198/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  sql:
    init:
      mode: always
server:
  port: 8080
